# –ò–º—è, —á—Ç–æ–±—ã –ø—Ä–µ–¥—Å—Ç–∞–≤–∏—Ç—å—Å—è Config Server'—É –∏ Eureka
spring:
  application:
    name: eureka-server
  
  # üëá –í–û–¢ –≠–¢–û –ò–°–ü–†–ê–í–õ–ï–ù–ò–ï üëá
  # –£–∫–∞–∑—ã–≤–∞–µ–º, –æ—Ç–∫—É–¥–∞ –∏–º–ø–æ—Ä—Ç–∏—Ä–æ–≤–∞—Ç—å –≤–Ω–µ—à–Ω–∏–µ –Ω–∞—Å—Ç—Ä–æ–π–∫–∏.
  # –≠—Ç–æ –Ω—É–∂–Ω–æ —Å–¥–µ–ª–∞—Ç—å –¥–æ —Ç–æ–≥–æ, –∫–∞–∫ –±—É–¥—É—Ç –ø—Ä–∏–º–µ–Ω–µ–Ω—ã –æ—Å—Ç–∞–ª—å–Ω—ã–µ –∫–æ–Ω—Ñ–∏–≥–∏.
  config:
    import: "optional:configserver:http://localhost:8888"